--------------------------------------------------------
--  Fichier créé - jeudi-mai-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENT
--------------------------------------------------------

  CREATE TABLE "SYLLA"."AGENT" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_DE_NAISSANCE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ARME
--------------------------------------------------------

  CREATE TABLE "SYLLA"."ARME" 
   (	"NM1" VARCHAR2(20 BYTE), 
	"TY1" VARCHAR2(20 BYTE), 
	"NUM1" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUDGET
--------------------------------------------------------

  CREATE TABLE "SYLLA"."BUDGET" 
   (	"NUMR" VARCHAR2(20 BYTE), 
	"DATER" VARCHAR2(20 BYTE), 
	"SOMMER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "SYLLA"."CATEGORIES" 
   (	"ID" NUMBER, 
	"POSTE" VARCHAR2(20 BYTE), 
	"GRADE" VARCHAR2(20 BYTE), 
	"NOTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CELLULE
--------------------------------------------------------

  CREATE TABLE "SYLLA"."CELLULE" 
   (	"NUM" VARCHAR2(20 BYTE), 
	"DATEEN" VARCHAR2(20 BYTE), 
	"DATESO" VARCHAR2(20 BYTE), 
	"DISPO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CERTIFICAT
--------------------------------------------------------

  CREATE TABLE "SYLLA"."CERTIFICAT" 
   (	"IDCER" VARCHAR2(20 BYTE), 
	"NOMCER" VARCHAR2(20 BYTE), 
	"PRENOMCER" VARCHAR2(20 BYTE), 
	"NOMPERE" VARCHAR2(20 BYTE), 
	"DATESOR" VARCHAR2(20 BYTE), 
	"ADRESSERES" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITOYEN
--------------------------------------------------------

  CREATE TABLE "SYLLA"."CITOYEN" 
   (	"ID" NUMBER, 
	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETENU
--------------------------------------------------------

  CREATE TABLE "SYLLA"."DETENU" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOCUMENTCIN
--------------------------------------------------------

  CREATE TABLE "SYLLA"."DOCUMENTCIN" 
   (	"IDC" VARCHAR2(20 BYTE), 
	"NOMC" VARCHAR2(20 BYTE), 
	"PRENOMC" VARCHAR2(20 BYTE), 
	"DATEC" VARCHAR2(20 BYTE), 
	"LIEUC" VARCHAR2(20 BYTE), 
	"ADRESSEC" VARCHAR2(20 BYTE), 
	"METIERC" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAINTENANCE
--------------------------------------------------------

  CREATE TABLE "SYLLA"."MAINTENANCE" 
   (	"NUMM" VARCHAR2(20 BYTE), 
	"DATEM" VARCHAR2(20 BYTE), 
	"TYPEM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MISSION
--------------------------------------------------------

  CREATE TABLE "SYLLA"."MISSION" 
   (	"ID" NUMBER, 
	"NUMERO" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PASSEPORTDOC
--------------------------------------------------------

  CREATE TABLE "SYLLA"."PASSEPORTDOC" 
   (	"IDP" VARCHAR2(20 BYTE), 
	"CINP" VARCHAR2(20 BYTE), 
	"NOMP" VARCHAR2(20 BYTE), 
	"PRENOMP" VARCHAR2(20 BYTE), 
	"DATEP" VARCHAR2(20 BYTE), 
	"ADRESSEP" VARCHAR2(20 BYTE), 
	"METIERP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "SYLLA"."RECLAMATION" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"NOMR" VARCHAR2(20 BYTE), 
	"PRENOMR" VARCHAR2(20 BYTE), 
	"ADRESSER" VARCHAR2(20 BYTE), 
	"TELR" VARCHAR2(20 BYTE), 
	"DATER" VARCHAR2(20 BYTE), 
	"RECL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULE
--------------------------------------------------------

  CREATE TABLE "SYLLA"."VEHICULE" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NUM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYLLA.AGENT
SET DEFINE OFF;
Insert into SYLLA.AGENT (CIN,NOM,PRENOM,DATE_DE_NAISSANCE) values ('44','sdsfdsds','aaa','04-JAN-00');
Insert into SYLLA.AGENT (CIN,NOM,PRENOM,DATE_DE_NAISSANCE) values ('123456789','hsine','yuery','11-JAN-04');
REM INSERTING into SYLLA.ARME
SET DEFINE OFF;
Insert into SYLLA.ARME (NM1,TY1,NUM1) values (null,null,null);
Insert into SYLLA.ARME (NM1,TY1,NUM1) values (null,null,null);
Insert into SYLLA.ARME (NM1,TY1,NUM1) values (null,null,null);
Insert into SYLLA.ARME (NM1,TY1,NUM1) values (null,null,null);
Insert into SYLLA.ARME (NM1,TY1,NUM1) values (null,null,null);
Insert into SYLLA.ARME (NM1,TY1,NUM1) values ('5454','wwet','yrey');
Insert into SYLLA.ARME (NM1,TY1,NUM1) values ('rettr','ret','ert');
REM INSERTING into SYLLA.BUDGET
SET DEFINE OFF;
Insert into SYLLA.BUDGET (NUMR,DATER,SOMMER) values ('1548','05/01/2003','1879');
Insert into SYLLA.BUDGET (NUMR,DATER,SOMMER) values ('fff','01/01/2003','ds');
Insert into SYLLA.BUDGET (NUMR,DATER,SOMMER) values ('456','02/01/2000','jj');
REM INSERTING into SYLLA.CATEGORIES
SET DEFINE OFF;
Insert into SYLLA.CATEGORIES (ID,POSTE,GRADE,NOTE) values ('12355','Brigadier','2 Etoile','12');
Insert into SYLLA.CATEGORIES (ID,POSTE,GRADE,NOTE) values ('7','officier de police','1 Etoile','4');
REM INSERTING into SYLLA.CELLULE
SET DEFINE OFF;
Insert into SYLLA.CELLULE (NUM,DATEEN,DATESO,DISPO) values ('777','04/01/2000','04/01/2000','mm');
REM INSERTING into SYLLA.CERTIFICAT
SET DEFINE OFF;
Insert into SYLLA.CERTIFICAT (IDCER,NOMCER,PRENOMCER,NOMPERE,DATESOR,ADRESSERES) values (null,null,null,null,'01/01/2000',null);
REM INSERTING into SYLLA.CITOYEN
SET DEFINE OFF;
Insert into SYLLA.CITOYEN (ID,CIN,NOM,PRENOM,AGE) values ('4','178','awa','sylla','19');
Insert into SYLLA.CITOYEN (ID,CIN,NOM,PRENOM,AGE) values ('1','15','keren','mputu','19');
Insert into SYLLA.CITOYEN (ID,CIN,NOM,PRENOM,AGE) values ('2','14','mouhamed','diouf','21');
Insert into SYLLA.CITOYEN (ID,CIN,NOM,PRENOM,AGE) values ('5','198745632','achref','hyture','25');
REM INSERTING into SYLLA.DETENU
SET DEFINE OFF;
Insert into SYLLA.DETENU (CIN,PRENOM,NOM,ADRESSE) values ('54','aaa','bbb','bnbb');
Insert into SYLLA.DETENU (CIN,PRENOM,NOM,ADRESSE) values ('54','aaa','bbb','bnbb');
Insert into SYLLA.DETENU (CIN,PRENOM,NOM,ADRESSE) values ('98','fhty','rtg','rt');
REM INSERTING into SYLLA.DOCUMENTCIN
SET DEFINE OFF;
Insert into SYLLA.DOCUMENTCIN (IDC,NOMC,PRENOMC,DATEC,LIEUC,ADRESSEC,METIERC,SEXE) values (null,null,null,'01/01/2000',null,null,null,'Homme');
Insert into SYLLA.DOCUMENTCIN (IDC,NOMC,PRENOMC,DATEC,LIEUC,ADRESSEC,METIERC,SEXE) values ('4','yuyuyr','lkm,','04/01/2000','km','kjm,','km,','Homme');
Insert into SYLLA.DOCUMENTCIN (IDC,NOMC,PRENOMC,DATEC,LIEUC,ADRESSEC,METIERC,SEXE) values ('123456789','hsine','jhjh','01/01/2000','eytery','rtyrtu','rytyrty','Homme');
Insert into SYLLA.DOCUMENTCIN (IDC,NOMC,PRENOMC,DATEC,LIEUC,ADRESSEC,METIERC,SEXE) values ('1897456','awa','sylla','01/01/2004','tunis','etudiante','ariana','Femme');
REM INSERTING into SYLLA.MAINTENANCE
SET DEFINE OFF;
Insert into SYLLA.MAINTENANCE (NUMM,DATEM,TYPEM) values ('55','01/01/2003','df');
Insert into SYLLA.MAINTENANCE (NUMM,DATEM,TYPEM) values ('hbn','03/01/2000','uyhj');
REM INSERTING into SYLLA.MISSION
SET DEFINE OFF;
Insert into SYLLA.MISSION (ID,NUMERO,TYPE,DESCRIPTION) values ('2','1','ewds','redsfdsfgfgf');
Insert into SYLLA.MISSION (ID,NUMERO,TYPE,DESCRIPTION) values ('1','123','voiture','ghbvn');
Insert into SYLLA.MISSION (ID,NUMERO,TYPE,DESCRIPTION) values ('3','88','awa','sssaa');
REM INSERTING into SYLLA.PASSEPORTDOC
SET DEFINE OFF;
Insert into SYLLA.PASSEPORTDOC (IDP,CINP,NOMP,PRENOMP,DATEP,ADRESSEP,METIERP) values (null,null,null,null,'01/01/2000',null,null);
Insert into SYLLA.PASSEPORTDOC (IDP,CINP,NOMP,PRENOMP,DATEP,ADRESSEP,METIERP) values (null,null,null,null,'01/01/2000',null,null);
Insert into SYLLA.PASSEPORTDOC (IDP,CINP,NOMP,PRENOMP,DATEP,ADRESSEP,METIERP) values ('4','454','kj','n','04-01-2000','jjk','kjkj');
Insert into SYLLA.PASSEPORTDOC (IDP,CINP,NOMP,PRENOMP,DATEP,ADRESSEP,METIERP) values ('4','454','kj','n','04-01-2000','jjk','kjmmm');
Insert into SYLLA.PASSEPORTDOC (IDP,CINP,NOMP,PRENOMP,DATEP,ADRESSEP,METIERP) values ('4','454','kj','n','04-01-2000','jjk','kllll');
Insert into SYLLA.PASSEPORTDOC (IDP,CINP,NOMP,PRENOMP,DATEP,ADRESSEP,METIERP) values ('lk,','55','jhn,','kj,','03/01/2000','lm','lk');
Insert into SYLLA.PASSEPORTDOC (IDP,CINP,NOMP,PRENOMP,DATEP,ADRESSEP,METIERP) values (null,null,null,null,'01/01/2000',null,null);
Insert into SYLLA.PASSEPORTDOC (IDP,CINP,NOMP,PRENOMP,DATEP,ADRESSEP,METIERP) values (null,null,null,null,'01/01/2000',null,null);
Insert into SYLLA.PASSEPORTDOC (IDP,CINP,NOMP,PRENOMP,DATEP,ADRESSEP,METIERP) values (null,null,null,null,'01/01/2000',null,null);
Insert into SYLLA.PASSEPORTDOC (IDP,CINP,NOMP,PRENOMP,DATEP,ADRESSEP,METIERP) values ('vm156','12345678','mtiraoui','hsine','01/01/2006','ariana','etudiant');
REM INSERTING into SYLLA.RECLAMATION
SET DEFINE OFF;
Insert into SYLLA.RECLAMATION (CIN,NOMR,PRENOMR,ADRESSER,TELR,DATER,RECL) values (null,null,null,null,null,'01/01/2000',null);
Insert into SYLLA.RECLAMATION (CIN,NOMR,PRENOMR,ADRESSER,TELR,DATER,RECL) values ('77','kjn,','jhbn ','ijk','44','05/01/2000','kj');
REM INSERTING into SYLLA.VEHICULE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MISSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYLLA"."MISSION_PK" ON "SYLLA"."MISSION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CITOYEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYLLA"."CITOYEN_PK" ON "SYLLA"."CITOYEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MISSION
--------------------------------------------------------

  ALTER TABLE "SYLLA"."MISSION" ADD CONSTRAINT "MISSION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYLLA"."MISSION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITOYEN
--------------------------------------------------------

  ALTER TABLE "SYLLA"."CITOYEN" ADD CONSTRAINT "CITOYEN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYLLA"."CITOYEN" MODIFY ("ID" NOT NULL ENABLE);
